# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1271, 920)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ERRORFrame = QtWidgets.QFrame(self.top_bar)
        self.ERRORFrame.setMaximumSize(QtCore.QSize(450, 16777215))
        self.ERRORFrame.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border-radius: 5px;")
        self.ERRORFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ERRORFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ERRORFrame.setObjectName("ERRORFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ERRORFrame)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ERRORLabel = QtWidgets.QLabel(self.ERRORFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ERRORLabel.setFont(font)
        self.ERRORLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ERRORLabel.setObjectName("ERRORLabel")
        self.horizontalLayout_3.addWidget(self.ERRORLabel)
        self.ERRORXButton = QtWidgets.QPushButton(self.ERRORFrame)
        self.ERRORXButton.setMaximumSize(QtCore.QSize(20, 20))
        self.ERRORXButton.setStyleSheet("QPushButton {\n"
"    border-raadius: 5px;\n"
"    background-position: centre;\n"
"    border: 2px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 234, 70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(255, 234, 70);\n"
"}")
        self.ERRORXButton.setObjectName("ERRORXButton")
        self.horizontalLayout_3.addWidget(self.ERRORXButton)
        self.horizontalLayout_2.addWidget(self.ERRORFrame)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("background-color: rgb(143, 143, 143);\n"
"")
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MAINLabel = QtWidgets.QFrame(self.content)
        self.MAINLabel.setMaximumSize(QtCore.QSize(1500, 750))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MAINLabel.setFont(font)
        self.MAINLabel.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.MAINLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MAINLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MAINLabel.setObjectName("MAINLabel")
        self.FROMAddLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.FROMAddLabel.setGeometry(QtCore.QRect(20, 270, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FROMAddLabel.setFont(font)
        self.FROMAddLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid  rgb(170, 255, 255);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.FROMAddLabel.setText("")
        self.FROMAddLabel.setMaxLength(100)
        self.FROMAddLabel.setObjectName("FROMAddLabel")
        self.ADDFLIGHTButton = QtWidgets.QPushButton(self.MAINLabel)
        self.ADDFLIGHTButton.setGeometry(QtCore.QRect(1080, 270, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ADDFLIGHTButton.setFont(font)
        self.ADDFLIGHTButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 255, 255);\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(170, 255, 255);\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.ADDFLIGHTButton.setObjectName("ADDFLIGHTButton")
        self.SETTINGSIcon = QtWidgets.QFrame(self.MAINLabel)
        self.SETTINGSIcon.setGeometry(QtCore.QRect(940, 460, 291, 291))
        self.SETTINGSIcon.setStyleSheet("background-image: url(:/LOGO/img/setting.jpg);")
        self.SETTINGSIcon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SETTINGSIcon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SETTINGSIcon.setObjectName("SETTINGSIcon")
        self.label = QtWidgets.QLabel(self.MAINLabel)
        self.label.setGeometry(QtCore.QRect(30, 200, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.DELETEFLIGHTButton = QtWidgets.QPushButton(self.MAINLabel)
        self.DELETEFLIGHTButton.setGeometry(QtCore.QRect(180, 360, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DELETEFLIGHTButton.setFont(font)
        self.DELETEFLIGHTButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(17, 217, 217);\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(17, 217, 217);\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.DELETEFLIGHTButton.setObjectName("DELETEFLIGHTButton")
        self.ADDPLANEButton = QtWidgets.QPushButton(self.MAINLabel)
        self.ADDPLANEButton.setGeometry(QtCore.QRect(670, 580, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ADDPLANEButton.setFont(font)
        self.ADDPLANEButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 146, 208);\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 146, 208);\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(35, 35, 35);\n"
"}\n"
"")
        self.ADDPLANEButton.setObjectName("ADDPLANEButton")
        self.DELETEPLANEButton = QtWidgets.QPushButton(self.MAINLabel)
        self.DELETEPLANEButton.setGeometry(QtCore.QRect(190, 650, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DELETEPLANEButton.setFont(font)
        self.DELETEPLANEButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(12, 143, 143);\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 143, 143);\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(35, 35, 35);\n"
"}\n"
"")
        self.DELETEPLANEButton.setObjectName("DELETEPLANEButton")
        self.TOAddLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.TOAddLabel.setGeometry(QtCore.QRect(170, 270, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TOAddLabel.setFont(font)
        self.TOAddLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid  rgb(170, 255, 255);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.TOAddLabel.setText("")
        self.TOAddLabel.setMaxLength(100)
        self.TOAddLabel.setObjectName("TOAddLabel")
        self.DATEAddLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.DATEAddLabel.setGeometry(QtCore.QRect(320, 270, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.DATEAddLabel.setFont(font)
        self.DATEAddLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid  rgb(170, 255, 255);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.DATEAddLabel.setText("")
        self.DATEAddLabel.setMaxLength(100)
        self.DATEAddLabel.setObjectName("DATEAddLabel")
        self.TIMEAddLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.TIMEAddLabel.setGeometry(QtCore.QRect(470, 270, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TIMEAddLabel.setFont(font)
        self.TIMEAddLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid  rgb(170, 255, 255);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.TIMEAddLabel.setText("")
        self.TIMEAddLabel.setMaxLength(100)
        self.TIMEAddLabel.setObjectName("TIMEAddLabel")
        self.FLIGHTNUMBERAddLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.FLIGHTNUMBERAddLabel.setGeometry(QtCore.QRect(620, 270, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FLIGHTNUMBERAddLabel.setFont(font)
        self.FLIGHTNUMBERAddLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid  rgb(170, 255, 255);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.FLIGHTNUMBERAddLabel.setText("")
        self.FLIGHTNUMBERAddLabel.setMaxLength(100)
        self.FLIGHTNUMBERAddLabel.setObjectName("FLIGHTNUMBERAddLabel")
        self.PLANENUMBERAddFlightLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.PLANENUMBERAddFlightLabel.setGeometry(QtCore.QRect(770, 270, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PLANENUMBERAddFlightLabel.setFont(font)
        self.PLANENUMBERAddFlightLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid  rgb(170, 255, 255);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.PLANENUMBERAddFlightLabel.setText("")
        self.PLANENUMBERAddFlightLabel.setMaxLength(100)
        self.PLANENUMBERAddFlightLabel.setObjectName("PLANENUMBERAddFlightLabel")
        self.PRICEAddLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.PRICEAddLabel.setGeometry(QtCore.QRect(920, 270, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PRICEAddLabel.setFont(font)
        self.PRICEAddLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid  rgb(170, 255, 255);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.PRICEAddLabel.setText("")
        self.PRICEAddLabel.setMaxLength(100)
        self.PRICEAddLabel.setObjectName("PRICEAddLabel")
        self.Line1 = QtWidgets.QLabel(self.MAINLabel)
        self.Line1.setGeometry(QtCore.QRect(30, 230, 1021, 20))
        self.Line1.setStyleSheet("color: rgb(255, 255, 255);")
        self.Line1.setObjectName("Line1")
        self.FLIGHTNUMBERDeleteLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.FLIGHTNUMBERDeleteLabel.setGeometry(QtCore.QRect(20, 360, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FLIGHTNUMBERDeleteLabel.setFont(font)
        self.FLIGHTNUMBERDeleteLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(17, 217, 217);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.FLIGHTNUMBERDeleteLabel.setText("")
        self.FLIGHTNUMBERDeleteLabel.setMaxLength(100)
        self.FLIGHTNUMBERDeleteLabel.setObjectName("FLIGHTNUMBERDeleteLabel")
        self.Line2 = QtWidgets.QLabel(self.MAINLabel)
        self.Line2.setGeometry(QtCore.QRect(40, 530, 631, 20))
        self.Line2.setStyleSheet("color: rgb(255, 255, 255);")
        self.Line2.setObjectName("Line2")
        self.label_4 = QtWidgets.QLabel(self.MAINLabel)
        self.label_4.setGeometry(QtCore.QRect(50, 500, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.PLANENUMBERAddPlaneLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.PLANENUMBERAddPlaneLabel.setGeometry(QtCore.QRect(30, 580, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PLANENUMBERAddPlaneLabel.setFont(font)
        self.PLANENUMBERAddPlaneLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 146, 208);\n"
"    color: rgb(200,200,200);\n"
"}\n"
"")
        self.PLANENUMBERAddPlaneLabel.setText("")
        self.PLANENUMBERAddPlaneLabel.setMaxLength(100)
        self.PLANENUMBERAddPlaneLabel.setObjectName("PLANENUMBERAddPlaneLabel")
        self.YEAROFPRDAddLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.YEAROFPRDAddLabel.setGeometry(QtCore.QRect(180, 580, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.YEAROFPRDAddLabel.setFont(font)
        self.YEAROFPRDAddLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 146, 208);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.YEAROFPRDAddLabel.setText("")
        self.YEAROFPRDAddLabel.setMaxLength(100)
        self.YEAROFPRDAddLabel.setObjectName("YEAROFPRDAddLabel")
        self.FLIGHTSMILESAddLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.FLIGHTSMILESAddLabel.setGeometry(QtCore.QRect(340, 580, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FLIGHTSMILESAddLabel.setFont(font)
        self.FLIGHTSMILESAddLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 146, 208);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.FLIGHTSMILESAddLabel.setText("")
        self.FLIGHTSMILESAddLabel.setMaxLength(100)
        self.FLIGHTSMILESAddLabel.setObjectName("FLIGHTSMILESAddLabel")
        self.CAPACITYAddLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.CAPACITYAddLabel.setGeometry(QtCore.QRect(500, 580, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CAPACITYAddLabel.setFont(font)
        self.CAPACITYAddLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 146, 208);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.CAPACITYAddLabel.setText("")
        self.CAPACITYAddLabel.setMaxLength(100)
        self.CAPACITYAddLabel.setObjectName("CAPACITYAddLabel")
        self.PLANENUMBERDeleteLabel = QtWidgets.QLineEdit(self.MAINLabel)
        self.PLANENUMBERDeleteLabel.setGeometry(QtCore.QRect(30, 650, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PLANENUMBERDeleteLabel.setFont(font)
        self.PLANENUMBERDeleteLabel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 8px;    \n"
"    padding: 15 px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(12, 143, 143);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.PLANENUMBERDeleteLabel.setText("")
        self.PLANENUMBERDeleteLabel.setMaxLength(100)
        self.PLANENUMBERDeleteLabel.setObjectName("PLANENUMBERDeleteLabel")
        self.ADMINIcon = QtWidgets.QFrame(self.MAINLabel)
        self.ADMINIcon.setGeometry(QtCore.QRect(510, 10, 231, 211))
        self.ADMINIcon.setStyleSheet("background-image: url(:/LOGO/img/admin.png);")
        self.ADMINIcon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ADMINIcon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ADMINIcon.setObjectName("ADMINIcon")
        self.horizontalLayout.addWidget(self.MAINLabel)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1271, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ERRORLabel.setText(_translate("MainWindow", "ERROR"))
        self.ERRORXButton.setText(_translate("MainWindow", "X"))
        self.FROMAddLabel.setPlaceholderText(_translate("MainWindow", "FROM"))
        self.ADDFLIGHTButton.setText(_translate("MainWindow", "ADD FLIGHT"))
        self.label.setText(_translate("MainWindow", "FLIGHT"))
        self.DELETEFLIGHTButton.setText(_translate("MainWindow", "DELETE FLIGHT"))
        self.ADDPLANEButton.setText(_translate("MainWindow", "ADD PLANE"))
        self.DELETEPLANEButton.setText(_translate("MainWindow", "DELETE PLANE"))
        self.TOAddLabel.setPlaceholderText(_translate("MainWindow", "TO"))
        self.DATEAddLabel.setPlaceholderText(_translate("MainWindow", "DATE"))
        self.TIMEAddLabel.setPlaceholderText(_translate("MainWindow", "TIME"))
        self.FLIGHTNUMBERAddLabel.setPlaceholderText(_translate("MainWindow", "FLIGHT NUMBER"))
        self.PLANENUMBERAddFlightLabel.setPlaceholderText(_translate("MainWindow", "PLANE NUMBER"))
        self.PRICEAddLabel.setPlaceholderText(_translate("MainWindow", "PRICE"))
        self.Line1.setText(_translate("MainWindow", "_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"))
        self.FLIGHTNUMBERDeleteLabel.setPlaceholderText(_translate("MainWindow", "FLIGHT NUMBER"))
        self.Line2.setText(_translate("MainWindow", "____________________________________________________________________________________________________________________________________________"))
        self.label_4.setText(_translate("MainWindow", "PLANE"))
        self.PLANENUMBERAddPlaneLabel.setPlaceholderText(_translate("MainWindow", "PLANE NUMBER"))
        self.YEAROFPRDAddLabel.setPlaceholderText(_translate("MainWindow", "YEAR OF PRODUCTION"))
        self.FLIGHTSMILESAddLabel.setPlaceholderText(_translate("MainWindow", "FLIGHTS MILES"))
        self.CAPACITYAddLabel.setPlaceholderText(_translate("MainWindow", "CAPACITY"))
        self.PLANENUMBERDeleteLabel.setPlaceholderText(_translate("MainWindow", "PLANE NUMBER"))
import file


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
