# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BuyTicket.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LOGINWindow(object):
    def setupUi(self, LOGINWindow):
        LOGINWindow.setObjectName("LOGINWindow")
        LOGINWindow.resize(1001, 845)
        LOGINWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(LOGINWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.INFOFrame = QtWidgets.QFrame(self.top_bar)
        self.INFOFrame.setMaximumSize(QtCore.QSize(450, 16777215))
        self.INFOFrame.setStyleSheet("background-color: rgb(170, 255, 127);\n"
                                     "border-radius: 5px;")
        self.INFOFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.INFOFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.INFOFrame.setObjectName("INFOFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.INFOFrame)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.INFOLabel = QtWidgets.QLabel(self.INFOFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.INFOLabel.setFont(font)
        self.INFOLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.INFOLabel.setObjectName("INFOLabel")
        self.horizontalLayout_3.addWidget(self.INFOLabel)
        self.INFOXButton = QtWidgets.QPushButton(self.INFOFrame)
        self.INFOXButton.setMaximumSize(QtCore.QSize(20, 20))
        self.INFOXButton.setStyleSheet("QPushButton {\n"
                                       "    border-raadius: 5px;\n"
                                       "    background-position: centre;\n"
                                       "    border: 2px solid;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(50, 50, 50);\n"
                                       "    color: rgb(255, 234, 70);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed {\n"
                                       "    background-color: rgb(35, 35, 35);\n"
                                       "    color: rgb(255, 234, 70);\n"
                                       "}")
        self.INFOXButton.setObjectName("INFOXButton")
        self.horizontalLayout_3.addWidget(self.INFOXButton)
        self.horizontalLayout_2.addWidget(self.INFOFrame)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("background-color: rgb(143, 143, 143);")
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PASSWORDLabel = QtWidgets.QFrame(self.content)
        self.PASSWORDLabel.setMaximumSize(QtCore.QSize(750, 550))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PASSWORDLabel.setFont(font)
        self.PASSWORDLabel.setStyleSheet("background-color: rgb(57, 57, 57);\n"
                                         "border-radius: 10px;")
        self.PASSWORDLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PASSWORDLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PASSWORDLabel.setObjectName("PASSWORDLabel")
        self.NUMBEROFPASSENGERSLabel = QtWidgets.QLineEdit(self.PASSWORDLabel)
        self.NUMBEROFPASSENGERSLabel.setGeometry(QtCore.QRect(130, 350, 461, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NUMBEROFPASSENGERSLabel.setFont(font)
        self.NUMBEROFPASSENGERSLabel.setStyleSheet("QLineEdit {\n"
                                                   "    border: 2px solid rgb(45,45,45);\n"
                                                   "    border-radius: 5px;    \n"
                                                   "    padding: 15 px;\n"
                                                   "    background-color: rgb(30,30,30);\n"
                                                   "    \n"
                                                   "    color: rgb(255, 255, 255);\n"
                                                   "}\n"
                                                   "\n"
                                                   "QLineEdit:hover {\n"
                                                   "    border: 2px solid rgb(55,55,55);\n"
                                                   "}\n"
                                                   "\n"
                                                   "QLineEdit:focus {\n"
                                                   "    border: 2px solid rgb(255,255,127);\n"
                                                   "    color: rgb(200,200,200)\n"
                                                   "}")
        self.NUMBEROFPASSENGERSLabel.setText("")
        self.NUMBEROFPASSENGERSLabel.setMaxLength(100)
        self.NUMBEROFPASSENGERSLabel.setObjectName("NUMBEROFPASSENGERSLabel")
        self.HANGLUGGAGEBox = QtWidgets.QCheckBox(self.PASSWORDLabel)
        self.HANGLUGGAGEBox.setGeometry(QtCore.QRect(280, 300, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.HANGLUGGAGEBox.setFont(font)
        self.HANGLUGGAGEBox.setStyleSheet("QCheckBox::indicator {\n"
                                          "    border: 3px solid rgb(100,100,100);\n"
                                          "    width: 15px;\n"
                                          "    height: 15px;\n"
                                          "    border-radius: 10px;\n"
                                          "    background-color: rgb(135, 135, 135);\n"
                                          "}\n"
                                          "\n"
                                          "QCheckBox::indicator:checked {\n"
                                          "    border: 3px solid rgb(255,255,0);\n"
                                          "    background-color: rgb(255, 255, 127);\n"
                                          "}")
        self.HANGLUGGAGEBox.setText("")
        self.HANGLUGGAGEBox.setObjectName("HANGLUGGAGEBox")
        self.BUYButton = QtWidgets.QPushButton(self.PASSWORDLabel)
        self.BUYButton.setGeometry(QtCore.QRect(240, 480, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BUYButton.setFont(font)
        self.BUYButton.setStyleSheet("QPushButton {\n"
                                     "    background-color: rgb(255, 255, 127);\n"
                                     "    border: 2px solid rgb(60,60,60);\n"
                                     "    border-radius: 5px;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     "    background-color: rgb(60, 60, 60);\n"
                                     "    border: 2px solid rgb(70,70,70);\n"
                                     "    border-radius: 5px;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed {\n"
                                     "    background-color: rgb(255, 255, 127);\n"
                                     "    border: 2px solid rgb(0,0,0);\n"
                                     "    border-radius: 5px;\n"
                                     "    \n"
                                     "    color: rgb(35, 35, 35);\n"
                                     "}")
        self.BUYButton.setObjectName("BUYButton")
        self.SURNAMELabel = QtWidgets.QLineEdit(self.PASSWORDLabel)
        self.SURNAMELabel.setGeometry(QtCore.QRect(370, 240, 221, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SURNAMELabel.setFont(font)
        self.SURNAMELabel.setStyleSheet("QLineEdit {\n"
                                        "    border: 2px solid rgb(45,45,45);\n"
                                        "    border-radius: 5px;    \n"
                                        "    padding: 15 px;\n"
                                        "    background-color: rgb(30,30,30);\n"
                                        "    \n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "\n"
                                        "QLineEdit:hover {\n"
                                        "    border: 2px solid rgb(55,55,55);\n"
                                        "}\n"
                                        "\n"
                                        "QLineEdit:focus {\n"
                                        "    border: 2px solid rgb(255,255,127);\n"
                                        "    color: rgb(200,200,200)\n"
                                        "}")
        self.SURNAMELabel.setText("")
        self.SURNAMELabel.setMaxLength(100)
        self.SURNAMELabel.setObjectName("SURNAMELabel")
        self.NAMELabel = QtWidgets.QLineEdit(self.PASSWORDLabel)
        self.NAMELabel.setGeometry(QtCore.QRect(129, 240, 221, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NAMELabel.setFont(font)
        self.NAMELabel.setStyleSheet("QLineEdit {\n"
                                     "    border: 2px solid rgb(45,45,45);\n"
                                     "    border-radius: 5px;    \n"
                                     "    padding: 15 px;\n"
                                     "    background-color: rgb(30,30,30);\n"
                                     "    \n"
                                     "    color: rgb(255, 255, 255);\n"
                                     "}\n"
                                     "\n"
                                     "QLineEdit:hover {\n"
                                     "    border: 2px solid rgb(55,55,55);\n"
                                     "}\n"
                                     "\n"
                                     "QLineEdit:focus {\n"
                                     "    border: 2px solid rgb(255,255,127);\n"
                                     "    color: rgb(200,200,200)\n"
                                     "}")
        self.NAMELabel.setText("")
        self.NAMELabel.setMaxLength(100)
        self.NAMELabel.setObjectName("NAMELabel")
        self.FLIGHTNUMBERLabel = QtWidgets.QLineEdit(self.PASSWORDLabel)
        self.FLIGHTNUMBERLabel.setGeometry(QtCore.QRect(130, 180, 461, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FLIGHTNUMBERLabel.setFont(font)
        self.FLIGHTNUMBERLabel.setStyleSheet("QLineEdit {\n"
                                             "    border: 2px solid rgb(45,45,45);\n"
                                             "    border-radius: 5px;    \n"
                                             "    padding: 15 px;\n"
                                             "    background-color: rgb(30,30,30);\n"
                                             "    \n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "}\n"
                                             "\n"
                                             "QLineEdit:hover {\n"
                                             "    border: 2px solid rgb(55,55,55);\n"
                                             "}\n"
                                             "\n"
                                             "QLineEdit:focus {\n"
                                             "    border: 2px solid rgb(255,255,127);\n"
                                             "    color: rgb(200,200,200)\n"
                                             "}")
        self.FLIGHTNUMBERLabel.setText("")
        self.FLIGHTNUMBERLabel.setMaxLength(100)
        self.FLIGHTNUMBERLabel.setObjectName("FLIGHTNUMBERLabel")
        self.label = QtWidgets.QLabel(self.PASSWORDLabel)
        self.label.setGeometry(QtCore.QRect(140, 290, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.UNDER15KGBox = QtWidgets.QCheckBox(self.PASSWORDLabel)
        self.UNDER15KGBox.setGeometry(QtCore.QRect(400, 300, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.UNDER15KGBox.setFont(font)
        self.UNDER15KGBox.setStyleSheet("QCheckBox::indicator {\n"
                                        "    border: 3px solid rgb(100,100,100);\n"
                                        "    width: 15px;\n"
                                        "    height: 15px;\n"
                                        "    border-radius: 10px;\n"
                                        "    background-color: rgb(135, 135, 135);\n"
                                        "}\n"
                                        "\n"
                                        "QCheckBox::indicator:checked {\n"
                                        "    border: 3px solid rgb(255,255,0);\n"
                                        "    background-color: rgb(255, 255, 127);\n"
                                        "}")
        self.UNDER15KGBox.setText("")
        self.UNDER15KGBox.setObjectName("UNDER15KGBox")
        self.OVER15KGBox = QtWidgets.QCheckBox(self.PASSWORDLabel)
        self.OVER15KGBox.setGeometry(QtCore.QRect(500, 300, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.OVER15KGBox.setFont(font)
        self.OVER15KGBox.setStyleSheet("QCheckBox::indicator {\n"
                                       "    border: 3px solid rgb(100,100,100);\n"
                                       "    width: 15px;\n"
                                       "    height: 15px;\n"
                                       "    border-radius: 10px;\n"
                                       "    background-color: rgb(135, 135, 135);\n"
                                       "}\n"
                                       "\n"
                                       "QCheckBox::indicator:checked {\n"
                                       "    border: 3px solid rgb(255,255,0);\n"
                                       "    background-color: rgb(255, 255, 127);\n"
                                       "}")
        self.OVER15KGBox.setText("")
        self.OVER15KGBox.setObjectName("OVER15KGBox")
        self.label_2 = QtWidgets.QLabel(self.PASSWORDLabel)
        self.label_2.setGeometry(QtCore.QRect(310, 300, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.PASSWORDLabel)
        self.label_3.setGeometry(QtCore.QRect(430, 300, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.PASSWORDLabel)
        self.label_4.setGeometry(QtCore.QRect(530, 300, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.LogoFrame = QtWidgets.QFrame(self.PASSWORDLabel)
        self.LogoFrame.setGeometry(QtCore.QRect(260, 0, 191, 171))
        self.LogoFrame.setStyleSheet("background-image: url(:/LOGO/img/logo.png);")
        self.LogoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LogoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LogoFrame.setObjectName("LogoFrame")
        self.label_5 = QtWidgets.QLabel(self.PASSWORDLabel)
        self.label_5.setGeometry(QtCore.QRect(460, 400, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.TOTALPRICELabel = QtWidgets.QLabel(self.PASSWORDLabel)
        self.TOTALPRICELabel.setGeometry(QtCore.QRect(520, 410, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.TOTALPRICELabel.setFont(font)
        self.TOTALPRICELabel.setStyleSheet("color: rgb(255, 85, 127);")
        self.TOTALPRICELabel.setObjectName("TOTALPRICELabel")
        self.TOTALPRICECURRENCYLabel = QtWidgets.QLabel(self.PASSWORDLabel)
        self.TOTALPRICECURRENCYLabel.setGeometry(QtCore.QRect(580, 410, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.TOTALPRICECURRENCYLabel.setFont(font)
        self.TOTALPRICECURRENCYLabel.setStyleSheet("color: rgb(255, 85, 127);")
        self.TOTALPRICECURRENCYLabel.setObjectName("TOTALPRICECURRENCYLabel")
        self.horizontalLayout.addWidget(self.PASSWORDLabel)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout.addWidget(self.bottom)
        LOGINWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LOGINWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1001, 18))
        self.menubar.setObjectName("menubar")
        LOGINWindow.setMenuBar(self.menubar)

        self.retranslateUi(LOGINWindow)
        QtCore.QMetaObject.connectSlotsByName(LOGINWindow)

    def retranslateUi(self, LOGINWindow):
        _translate = QtCore.QCoreApplication.translate
        LOGINWindow.setWindowTitle(_translate("LOGINWindow", "ByuTicket"))
        self.INFOLabel.setText(_translate("LOGINWindow", "THANK YOU FOR SHOPPING. HAVE A NICE FLIGHT!"))
        self.INFOXButton.setText(_translate("LOGINWindow", "X"))
        self.NUMBEROFPASSENGERSLabel.setPlaceholderText(_translate("LOGINWindow", "NUMBER OF PASSENGERS"))
        self.BUYButton.setText(_translate("LOGINWindow", "BUY"))
        self.SURNAMELabel.setPlaceholderText(_translate("LOGINWindow", "SURNAME"))
        self.NAMELabel.setPlaceholderText(_translate("LOGINWindow", "NAME"))
        self.FLIGHTNUMBERLabel.setPlaceholderText(_translate("LOGINWindow", "FLIGHT NUMBER"))
        self.label.setText(_translate("LOGINWindow", "LABEL CAPACITY:"))
        self.label_2.setText(_translate("LOGINWindow", "HAND LUGGAGE"))
        self.label_3.setText(_translate("LOGINWindow", "UNDER 15 KG"))
        self.label_4.setText(_translate("LOGINWindow", "OVER 15 KG"))
        self.label_5.setText(_translate("LOGINWindow", "TOTAL:"))
        self.TOTALPRICELabel.setText(_translate("LOGINWindow", "189 "))
        self.TOTALPRICECURRENCYLabel.setText(_translate("LOGINWindow", "€"))


import file

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LOGINWindow = QtWidgets.QMainWindow()
    ui = Ui_LOGINWindow()
    ui.setupUi(LOGINWindow)
    LOGINWindow.show()
    sys.exit(app.exec_())
